version: "3.7"

services:
  wordpress-db:
    volumes:
      - .mysql_data:/var/lib/mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: database_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: database_password

  wordpress:
    volumes:
      - ./wordpress:/var/www/html
    image: wordpress:latest
    ports:
      - 9000:80
    links:
      - wordpress-db
    depends_on:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: database_password
